string objectUri   # absolute URI of an object
string object      # OWL based description of object
string description # human-readable description
semantic_storage_interface_msgs/RosFile[] newFiles  # object related binary files
                   # (they must have unique file names; might be an empty array;
                   # pre-existing files with the same name will be overwritten; 
                   # other files will remain as they are)
---
bool success       # indicates whether request was successfully completed
string[] blobUris  # URIs of uploaded files
