geometry_msgs/Pose[] targetPoseVec

string targetType
int32 actorType #ASSEMBLY, WELDING
string associatedActor

string targetProperty

string description

string timeStamp
	
string semanticName

int32 targetId

string modelPath

bool isRobot
string kinematicModelPath

float64 speed

#welding parameters
float32 weldingCurrent
float32 weldingVoltage
float32 robotMovingSpeed
float32 spotWeldingTime

#nailing parameters
float64 distance

#sawing parameters
float64 rpm
