Class type		# basic information about physical entity entity
Class category		# Type of the model's category (e.g. tool, object, sensor, robot, ...)
string iri		# IRI of OWL individual
string name
string description
string shapeIri		# IRI of OntoBREP's Compound individual
string modelUrl		# URL of the JSON file that contains both BREP and triangulated model data on the web server. For example: "http://kb.local/rest/blob/store/part/tofas/mechanical-tree/mechanicaltree.json"
string sourceUrl	# URL of source model in blob store. (OCC's brep format, STEP, IGES)
