#parameters associated with dual arm pick and place with approach and end pose

geometry_msgs/Pose pickobject_grasp_approach
geometry_msgs/Pose pickobject_grasp
geometry_msgs/Pose pickobject_place_approach
geometry_msgs/Pose pickobject_assembly #final pose of that the robot tip moves to
geometry_msgs/Pose pickobject_final_pose #final pose of the OBJECT
geometry_msgs/Pose pick_execution_actor_resting
string pick_execution_actor
float32 pickobject_gripper_span
