#task parameters

process_im_msgs/GraspParameters       			grasp_parameters 
process_im_msgs/PlaceParameters       			place_parameters 
process_im_msgs/PickPlaceParameters   			pick_place_parameters 
process_im_msgs/PickPlaceEndPoseParameters   		pick_place_endpose_parameters 
process_im_msgs/PickPlaceApproachEndPoseParameters   	pick_place_approach_endpose_parameters 
process_im_msgs/PushDownParameters   			push_down_parameters 
process_im_msgs/MoveParameters        			move_parameters 
process_im_msgs/MoveToActorParameters 			move_to_actor_parameters 
process_im_msgs/WeldSpotParameters    			weld_spot_parameters 
process_im_msgs/WeldSeamParameters    			weld_seam_parameters
process_im_msgs/NailParameters    				nail_parameters
process_im_msgs/SawParameters    				saw_parameters
process_im_msgs/PickPlaceEndPoseParameters   disassemble_endpose_parameters
process_im_msgs/PickPlaceApproachEndPoseParameters   disassemble_approach_endpose_parameters

process_im_msgs/DualArmPickPlaceApproachEndPoseParameters  dual_arm_pick_place_approach_endpose_parameters
process_im_msgs/DualArmPickPlaceEndPoseParameters          dual_arm_pick_place_endpose_parameters
process_im_msgs/DualArmAssemblyAirEndPoseParameters        dual_arm_assembly_air_endpose_parameters
process_im_msgs/DualArmAssemblyGroundEndPoseParameters     dual_arm_assembly_ground_endpose_parameters
process_im_msgs/DualArmGraspParameters                     dual_arm_grasp_parameters
process_im_msgs/DualArmPlaceParameters                     dual_arm_place_parameters
process_im_msgs/DualArmPushParameters                      dual_arm_push_parameters
process_im_msgs/DualArmMoveParameters                      dual_arm_move_parameters
process_im_msgs/DualArmMoveActorParameters                 dual_arm_move_actor_parameters



